[[a.node_a.f]]
timing=1.0
text="[<>]"
fg="ywwy"

[[a.node_a.f]]
timing=1.0
text="[<>]"
fg="gggg"

[[a.node_b.f]]
timing=1.0
text="[&&]"
fg="ywwy"

[[a.node_b.f]]
timing=1.0
text="[&&]"
fg="gggg"

[values.colors]
g="grey"
y="yellow"
w="white"