registry="term:short_names"

[values]
"Data Doctor Pro"   = "DataDocPro"
"Data Doctor"       = "DataDoctor"
"Black Widow"       = "BlackWidow"
"Golem Stone"       = "GolemStone"
"Laser Satellite"   = "Laser Sat"
"Mobile Tower"      = "MobilTower"
"Sentinel 2.0"      = "Sentinel 2"
"Sentinel 3.0"      = "Sentinel 3"
"Turbo Deluxe"      = "Turbo DLX"
"Watchman SP"       = "WatchmanSP"
"Wolf Spider"       = "WolfSpider"
# "Attack Dog"    =
# "Ballista"      =
# "Bit Man"       =
# "Boss"          =
# "Bug"           =
# "Buzzbomb"      =
# "Catapult"      =
# "Clog"          =
# "Clog.02"       =
# "Clog.03"       =
# "Fiddle"        =
# "Fire Wall"     =
# "Golem Clay"    =
# "Golem Mud"     =
# "Guard Dog"     =
# "Guard Pup"     =
# "Guru"          =
# "Hack 2.0"      =
# "Hack 3.0"      =
# "Hack"          =
# "Heisenbug"     =
# "Logic Bomb"    =
# "Mandelbug"     =
# "Medic"         =
# "Memory Hog"    =
# "Radar"         =
# "Satellite"     =
# "Seeker 2.0"    =
# "Seeker 3.0"    =
# "Seeker"        =
# "Sensor"        =
# "Sentinel"      =
# "Slingshot"     =
# "Sonar"         =
# "Sumo"          =
# "Tarantula"     =
# "Tower"         =
# "Turbo"         =
# "Warden"        =
# "Warden+"       =
# "Warden++"      =
# "Watchman X"    =
# "Watchman"      =
# "Wizard"        =