[package]
name = "n_dit"
version = "0.1.0"
authors = ["Testare <testare.i9z@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aquamarine = "0.1.5"
crossterm = "0.20.0"
getset = "0.1.1"
itertools = "0.10.1"
lazy_static = "1.4.0"
pad = "0.1"
unicode-width = "0.1.8"
log = "0.4"
simplelog = "^0.10.0"

# Use for "cargo flamegraph"
# [profile.release]
# debug = true
