[package]
name = "n_dit"
version = "0.1.0"
authors = ["Testare <testare.i9z@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
old_game_core = { path = "old_game_core" }
game_core = { path = "game_core" }
log = "0.4"
simplelog = "^0.10.0"
serde_json = "1.0"

aquamarine = "0.1.5"
getset = "0.1.1"
itertools = "0.10.1"
# CLI Rendering
pad =  { git = "https://github.com/Testare/rust-pad" }
unicode-width = "0.1.8"
crossterm = { version = "0.20.0", features = ["event-stream"] }
taffy = "0.2"
thiserror = "1.0.40"
textwrap = "0.16.0"
toml = "0.7.6"
serde = { version = "1.0", feature = ["derive"] }

[dependencies.bevy]
version = "0.11"
default-features = false
features = [
    "bevy_asset",
    "filesystem_watcher",
    "bevy_scene",
    "bevy_audio",
    "animation"
]

[dev-dependencies]
test-log = "0.2.12"
env_logger = "*"

# Use for "cargo flamegraph"
# [profile.release]
# debug = true

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
