[package]
name = "n_dit"
version = "0.1.0"
authors = ["Testare <testare.i9z@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game_core = { path = "game_core" }
log = "0.4"
simplelog = "^0.10.0"
serde_json = "1.0"

aquamarine = "0.1.5"
getset = "0.1.1"
itertools = "0.10.1"
# CLI Rendering
pad =  { git = "https://github.com/Testare/rust-pad" }
unicode-width = "0.1.8"
crossterm = "0.20.0"
taffy = "0.1.0" # For some reason not building here? Even though you can se
bevy = "0.7"

# Use for "cargo flamegraph"
# [profile.release]
# debug = true
