[workspace]
members = ["crates/*"]
default-members = ["crates/n_dit"]
metadata.crane.name = "n_dit_workspace"
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Testare <testare.i9z@gmail.com>"]
repository = "https://github.com/Testare/n_dit"
rust-version = "1.78"
edition = "2021"

[patch.crates-io]
simplelog = { git = "https://github.com/aminya/simplelog.rs.git", branch = "patch-1" }
bevy_yarnspinner = { git = "https://github.com/wiggleforlife/YarnSpinner-Rust.git", branch = "main" }

[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
single_match = "allow"
too_many_arguments = "allow"
type_complexity = "allow"

[workspace.dependencies]
freeform = { version = "0.4", features = ["toml"] }
bevy_query_ext = "0.5"
bevy_yarnspinner = "0.4"
toml = "0.8.12"
workspace-hack = { version = "0.1", path = "crates/workspace-hack" }

[workspace.dependencies.bevy]
version = "0.15.0"
default-features = false
features = [
    "bevy_asset",
    "bevy_audio",
    "bevy_remote",
    "bevy_scene",
    "file_watcher",
    "mp3",
    "multi_threaded",
    "dynamic_linking",
]
