#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
if [ -n "$(command -v rg)" ] && ( [ -n "$(rg NOCOMMIT src)" ] || [ -n "$(rg NO_COMMIT src)" ] ) ; then 
    echo "ERROR: You have instances of NOCOMMIT statements"
    rg NOCOMMIT src
    rg NO_COMMIT src
    exit 2
fi
