#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
NC_ADDS="$(git diff --cached -G"NOCOMMIT|nocommit" | grep '^+' | grep -i nocommit)"
if [ -n "$NC_ADDS" ] ; then
    echo "ERROR: You have instances of NOCOMMIT statements"
    git diff --cached -G"NOCOMMIT|nocommit"
    exit 2
fi
