[package]
name = "charmi"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
toml.workspace = true
charmi_core.path = "../charmi_core"
charmi_macro.path = "../charmi_macro"
crossterm = "0.28.1"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
unicode-width = "0.2.0"
workspace-hack.workspace = true

[dev-dependencies]
test-log = "0.2.17"

[dependencies.clap]
version = "4.5.23"
features = ["derive"]

[[example]]
name = "demo"
path = "examples/demo.rs"
required-features = ["bevy/bevy_log"]
